package com.revature.exception;

class NewException extends ArithmeticException {
	public String getMessage() {
		return "You can't do that";
	}
}

public class ExceptionDemo {
	
	public static String hello() {
		return "Hello";
	}
	
	public static int divide() {
		return 1/0;
	}

	public static void main(String[] args) {
		
		try {
			System.out.println(divide());
		} catch (Exception e) {
			
		}

	}

}
