package com.revature.exception;

public class ExceptionDemo {
	
	public static String hello() {
		return "Hello";
	}
	
	public static int divide() {
		return 1/0;
	}

	public static void main(String[] args) {
		System.out.println(divide());
		try {
			
		} catch (Exception e) {
			
		}

	}

}
